
import Navbar from "@/components/Navbar";
import "./globals.css";
import "@/components/ThemeToogle.css";
import ThemeToggle from "@/components/ThemeToogle";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
      <Navbar/>
        {children}

      <ThemeToggle /> 
     
      </body>
    </html>
  );
}
